Repository BoostIO/BoostNote-App, pull requests merged in 2020-07, with the labels that each got.

#512 Add mobile app links
  readme.md
Labels: awaiting review :sparkle:, documentation 📚

#514 Fixed the table align
  src/components/atoms/MarkdownPreviewer.tsx
Labels: approved :+1:

#551 Update Slack invite link
  src/components/PreferencesModal/AboutTab.tsx
Labels: awaiting review :sparkle:

#524 Fix storage edit page not scrolling because of height not set on cont…
  src/components/atoms/PageContainer.tsx
Labels: awaiting review :sparkle:
