Repository BoostIO/BoostNote-App, pull requests merged in 2020-12, with the labels that each got.

#712 add save code to file button
  src/components/atoms/markdown/CodeFence.tsx
Labels: awaiting changes :pen:

#718 Show Plain Text in Preview for Unrecognized Languages (#698)
  src/components/atoms/MarkdownPreviewer.tsx
Labels: awaiting review :sparkle:

#677 Hompage Spanish translation (#462)
  homepage/locales/es.ts
Labels: approved :+1:

#715 Copy the attachment name in attachment page (#714)
  src/components/organisms/AttachmentList.tsx
Labels: awaiting changes :pen:

#750 Fix copy snippet without language
  src/components/atoms/MarkdownPreviewer.tsx
  src/components/atoms/markdown/CodeFence.tsx
Labels: awaiting review :sparkle:

#748 Fix bug for renaming folders in file system database
  src/lib/db/FSNoteDb.ts
  src/lib/string.ts
Labels: awaiting review :sparkle:

#744 Fix attachment urls being revoked too early
  src/components/organisms/NotePageToolbar.tsx
  src/lib/exports.ts
Labels: awaiting review :sparkle:
